name: run spec-parser

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: get spec-parser
        run: |
          git clone https://github.com/spdx/spec-parser/
          cd spec-parser
          python3 -m pip install -r requirements.txt
          python main.py -h
      - name: run spec-parser
        run: |
          cd spec-parser
          mkdir -p  /tmp/spec-parser.out
          python main.py \
              --gen-md \
              --gen-refs \
              --gen-rdf \
              --out-dir /tmp/spec-parser.out \
              ../model
      - uses: actions/upload-artifact@v3
        with:
          name: spec-parser.out
          path: /tmp/spec-parser.out
